module.exports = {
  GET_CURRENT_THEME: "getCurrentTheme",
  SET_CURRENT_THEME: "setCurrentTheme",
  RESTART_AND_UPDATE: "restartAndUpdate",
  UPDATE_DOWNLOADED: "updateDownloaded",
  UPDATE_PROGRESS: "updateProgress",
  UPDATE_ERROR: "updateError",
  UPDATE_NOT_AVAILABLE: "updateNotAvailable",
  UPDATE_AVAILABLE: "updateAvailable",
  CHECKING_FOR_UPDATE: "checkingForUpdate",
  DOWNLOAD_BEATMAP: "downloadBeatmap",
  DOWNLOAD_PROGRESS: "downloadProgress",
  DOWNLOAD_COMPLETE: "downloadComplete",
  DOWNLOAD_ERROR: "downloadError",
  CHANGE_DOWNLOAD_DIRECTORY: "changeDownloadDirectory",
  GET_DOWNLOAD_DIRECTORY: "getDownloadDirectory",
  BEATMAP_DOWNLOAD_ERROR: "beatmapDownloadError",
  PREVIEW_BEATMAP: "previewBeatmap",
  PREVIEW_LOADED: "previewLoaded",
  PREVIEW_ERROR: "previewError",
  LOAD_LIBRARY: "loadLibrary",
};
